apiVersion: v1
kind: Service
metadata:
  name: store
  namespace: store
  annotations:
    configsync.gke.io/cluster-name-selector: prod-ap-gke-ew2-0
spec:
  selector:
    app: store
  ports:
  - port: 8080
    targetPort: 8080
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  name: store
  namespace: store
  annotations:
    configsync.gke.io/cluster-name-selector: prod-ap-gke-ew2-0