---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-rw
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - 'get'
      - 'watch'
      - 'list'
      - 'create'
      - 'update'
      - 'patch'
  - nonResourceURLs:
      - '*'
    verbs:
      - 'get'
      - 'watch'
      - 'list'
      - 'create'
      - 'update'
      - 'patch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-rw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-rw
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: gke-editors@cloudmod-ff-test.gcp-ancoris.com