---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-ro
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - 'get'
      - 'watch'
      - 'list'
  - nonResourceURLs:
      - '*'
    verbs:
      - 'get'
      - 'watch'
      - 'list'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-ro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-ro
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: gke-readers@cloudmod-ff-test.gcp-ancoris.com
